### ISSUE TITLE
Expand ListingDetailItem on mobile with inner anchor tag

### ISSUE THREAD

**Issue by cliu02** [bloom-housing/ui-components#129]
This issue pertains to the automatic accordion expansion of ListingDetailItem on mobile screens. 

First, to understand the behavior: 
1. Go to https://dahlia-full.herokuapp.com/listings/a0W8H0000014LS9UAM?react=true on desktop.
2. Click on the banner anchor link "Learn more about who can apply." 
![Screenshot 2023-10-03 at 1 12 39 PM](https://github.com/bloom-housing/ui-components/assets/32694266/f65c4fce-964e-4b01-91cd-5d5b11b8e7e8)
3. This link jumps further down the page to an anchor tag within a ListingDetailItem called "Eligibility". The anchor tag is on "Check if you're eligible".
![Screenshot 2023-10-03 at 1 13 39 PM](https://github.com/bloom-housing/ui-components/assets/32694266/57b39e60-abb5-4c73-aca0-470b174f41bd)

However, on mobile screens, clicking on the banner link jumps down to the closed "Eligibility" accordion. This is the current behavior:
![Screenshot 2023-10-03 at 1 16 22 PM](https://github.com/bloom-housing/ui-components/assets/32694266/8f81ca35-5eee-44b2-a629-290ba7486e77)

We want this accordion to automatically expand so that the named anchor text within the accordion is viewable. This is the desired behavior: 
![Screenshot 2023-10-03 at 1 18 00 PM](https://github.com/bloom-housing/ui-components/assets/32694266/799c2741-e345-4eda-9895-85954d64fc60)

**Comment by yindipei** [comment]
@cliu02 @emilyjablonski : @slowbot messaged us about the complexity in engineering this. After a conversations with Bridget, we decided to remove the anchor link from the orange banner in the final design.
