### ISSUE TITLE
Language Pluralization 

### ISSUE THREAD

**Issue by cliu02** [bloom-housing/ui-components#150]
**Background:** This issue comes from DAHLIA ticket [DAH-2276](https://sfgovdt.jira.com/browse/DAH-2276) to fix DAHLIA bugs where different languages do not correctly display pluralization. For example, in English the string "Up to X units" should instead note "Up to 1 unit" if non-pluralized according to English language rules. DAHLIA has certain areas in the web application where there is an attempt to manually implement pluralizations, but there is complexity given how different languages have different pluralization rules. There is a request for a standard pluralization implementation. 

**Description:** Bloom UIC already uses the node-polygot npm package. This ticket is to implement the node-polyglot [pluralization feature](https://www.npmjs.com/package/node-polyglot#pluralization) in the [Bloom UIC translator](https://github.com/bloom-housing/ui-components/blob/main/src/helpers/translator.tsx). After implementation, strings should change depending on the specific language and its pluralization rules. For example, if the Bloom UIC translator is given the locale of English, then the string "Up to X units" should instead be "Up to 1 unit" if there is only one unit. This will ensure that DAHLIA and other Bloom UIC consumers have accurate language pluralization in multi-language content. 

This screenshot is an example of an area with pluralization bugs ("1 units" and "1 applicants are"):
![Screenshot 2024-04-22 at 10 07 35 AM](https://github.com/bloom-housing/ui-components/assets/32694266/55ad0849-a5db-4373-80a5-5899ea7710f4)

**Comment by sarahlazarich** [comment]
@emilyjablonski and @cliu02 to sync on defining the issue
