### ISSUE TITLE
Align ActionBlock component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#57]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/blocks-action-block--block-with-icon) to stories on [this PR](https://deploy-preview-44--storybook-bloom-dev.netlify.app/?path=/story/blocks-action-block--block-with-icon).

**Comment by sarahlazarich** [comment]
lgtm!
