### ISSUE TITLE
Align Button component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#59]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/actions-button--standard) to stories on [this PR](https://deploy-preview-45--storybook-bloom-dev.netlify.app/?path=/story/actions-button--standard).

**Comment by sarahlazarich** [comment]
lgtm!
