### ISSUE TITLE
Align StepHeader component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#64]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/headers-step-header--basic-dynamic) to stories on [this PR](https://deploy-preview-51--storybook-bloom-dev.netlify.app/?path=/story/headers-hero--with-listings).

**Comment by sarahlazarich** [comment]
these match!
