### ISSUE TITLE
Align LanguageNav component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#69]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
Compare the story on [dev](https://storybook.bloom.exygy.dev/?path=/story/navigation-languagenav--default) to the story on [this PR](https://deploy-preview-68--storybook-bloom-dev.netlify.app/?path=/story/navigation-languagenav--default).

You can also see it in some of the SiteHeader stories ([dev](https://storybook.bloom.exygy.dev/?path=/story/headers-site-header--with-language-and-mobile-notice) [PR](https://deploy-preview-68--storybook-bloom-dev.netlify.app/?path=/story/headers-site-header--with-language-and-mobile-notice)).

**Comment by sarahlazarich** [comment]
looks good!
