### ISSUE TITLE
Align ProgressNav component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#72]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/navigation-progress-nav-%F0%9F%9A%A9--default) and on [this PR](https://deploy-preview-70--storybook-bloom-dev.netlify.app/?path=/story/navigation-progress-nav-%F0%9F%9A%A9--default).

**Comment by sarahlazarich** [comment]
looks good!
