### ISSUE TITLE
Align AlertBox component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#73]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/notifications-alert-box--alert-box-alert) and on [this PR](https://deploy-preview-71--storybook-bloom-dev.netlify.app/?path=/story/notifications-alert-box--alert-box-alert).

**Comment by sarahlazarich** [comment]
QA'd!
