### ISSUE TITLE
Align LoadingOverlay component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#77]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/overlays-loading-overlay--default) and on [this PR](https://deploy-preview-76--storybook-bloom-dev.netlify.app/?path=/story/overlays-loading-overlay--default).

**Comment by sarahlazarich** [comment]
this looks the same!
