### ISSUE TITLE
Align ListingDetailHeader component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#81]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
There is a new [story](https://deploy-preview-80--storybook-bloom-dev.netlify.app/?path=/story/listing-listingdetailheader-%F0%9F%9A%A9--default) added you can compare to a [prod listing](https://housing.acgov.org/listing/19c24c16-3ecc-4a0e-996e-76b507cd6d71/alexan_webster_2330_webster_street_oakland_ca).

**Comment by sarahlazarich** [comment]
lgtm.
