### ISSUE TITLE
Align the GridSection component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#83]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/sections-grid-section--default-three-columns) and on [this PR](https://deploy-preview-82--storybook-bloom-dev.netlify.app/?path=/story/sections-grid-section--default-three-columns).

The edit story will look different, bc now there is actually an edit button :)

**Comment by sarahlazarich** [comment]
lgtm
