### ISSUE TITLE
Align Description component with Detroit updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#85]
Make updates to these component(s) so that the UIC version support the customizations that were made in Detroit. This is a subticket of the [overview ticket](https://github.com/bloom-housing/bloom/issues/3283).

QA Notes:
Check out listing detail pages and the information grid under the `Features` section and ensure there are no regressions comparing against production.

There is one expected change to use what is in Detroit, which is to extend the left border the full height of the title.

(New style)
![Screenshot 2023-03-13 at 6 11 03 PM](https://user-images.githubusercontent.com/65367387/224859368-0e925361-1927-40dd-8669-344dde932ce8.png)

(Old style)
![Screenshot 2023-03-13 at 6 11 21 PM](https://user-images.githubusercontent.com/65367387/224859382-2bbaa3a1-4b45-49e3-9e94-917d6a15927d.png)

**Comment by sarahlazarich** [comment]
the information grid on the prod listings matches the (new style) image.
