### ISSUE TITLE
[Bug] Footer links are stacked on top of each other

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/ui-components#93]
The links on the footer are now aligned on top of each other instead of in a row in desktop.

Current:
![image](https://user-images.githubusercontent.com/42942267/228620364-085e255f-6d7e-4101-b84e-155d10366bab.png)

Previous:
![image](https://user-images.githubusercontent.com/42942267/228620476-4df3ec7b-e67a-42d3-8c2b-c3a53bf43bf1.png)

**Comment by sarahlazarich** [comment]
QA'd at https://storybook.bloom.exygy.dev/?path=/story/footers-site-footer--footer-many-links -- looks good!
