### ISSUE TITLE
Remove references to cloudinary

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/ui-components#98]
Following a request from Doorway, we need to remove references to Cloudinary from UIC as they are shifting to setup AWS.

After both the [UIC](https://github.com/bloom-housing/ui-components/pull/97) and [core](https://github.com/bloom-housing/bloom/pull/3393) PRs go in, the QA notes:
Ensure you can upload a photo to a listing in [partners](https://partners.bloom.exygy.dev/sign-in).

**Comment by sarahlazarich** [comment]
Qa'd on [this listing](https://partners.bloom.exygy.dev/listings/838e93ee-6797-4e26-8dfa-cbf1b4f43ad5) - looks good!
